
    drop table sample if exists;

    create table sample (
        id bigint generated by default as identity,
        value varchar(100) not null,
        version bigint not null,
        primary key (id)
    );
