CREATE SEQUENCE PUBLIC.SAMPLE_SEQ START WITH 1;
CREATE CACHED TABLE PUBLIC.SAMPLE(
    ID BIGINT NOT NULL,
    VALUE VARCHAR(100) NOT NULL,
    VERSION BIGINT NOT NULL
);
ALTER TABLE PUBLIC.SAMPLE ADD CONSTRAINT PUBLIC.SAMPLE_PK PRIMARY KEY(ID);
